### PR TITLE
fix: simplify response parsing in PanelChatPrompt

### LINKED ISSUE #16: Markdown Conversion Errors in History Prompts
Hello,

I encountered two issues during use:

1. The fetched history prompts contain multiple invalid escape characters:

image

2. The fetched history prompt is missing `\n`.

These two issues lead to incorrect context formatting, which can cause the large model to output content in the wrong format, leading to chat panel display errors.

After debugging, I found that these two issues were caused by the `turndown` conversion process.

I made a simple modification to the code, and everything works fine. My solution was to skip the JSX -> Markdown conversion and directly output the markdown format provided by VSCode.

image

Why is there this conversion from Markdown -> JSX -> HTML -> Markdown?

### PR DESCRIPTION
**Pull request by Hazi7**
fixes #16

### CODE REVIEW

File: src/panel-chat.ts [hunk 1]
```diff
@@ -153,7 +153,7 @@ class PanelChatParticipant {
       messages.push({ role: "user", content: request.prompt });
 
       // Generate the chat response
-      const stream = await streamText({
```
Comment (mohankumarelec) [inline src/panel-chat.ts:156]: Can you please remove this change, since streamText returns a promise and await is required.
Thanks

Comment (Hazi7) [reply src/panel-chat.ts:156]: This seems to be just a synchronous method, does not return a Promise.

- [SDK Example:](https://sdk.vercel.ai/docs/reference/ai-sdk-core/stream-text#streamtext)
image

- [Source Code](https://github.com/vercel/ai/blob/main/packages/ai/core/generate-text/stream-text.ts)
```ts
@return
A result object for accessing different stream types and additional information.
 */
export function streamText<TOOLS extends Record<string, CoreTool>>({
  model,
  tools,
  toolChoice,
  system,
  prompt,
  messages,
  maxRetries,
  abortSignal,
  headers,
  maxSteps = 1,
  experimental_continueSteps: continueSteps = false,
  experimental_telemetry: telemetry,
  experimental_providerMetadata: providerMetadata,
  experimental_toolCallStreaming: toolCallStreaming = false,
  experimental_activeTools: activeTools,
  experimental_repairToolCall: repairToolCall,
  experimental_transform: transform,
  onChunk,
  onFinish,
  onStepFinish,
  _internal: {
    now = originalNow,
    generateId = originalGenerateId,
    currentDate = () => new Date(),
  } = {},
  ...settings
}: CallSettings &
  Prompt & {
    /**
The language model to use.
     */
    model: LanguageModel;

    /**
The tools that the model can call. The model needs to support calling tools.
    */
    tools?: TOOLS;

    /**
The tool choice strategy. Default: 'auto'.
     */
    toolChoice?: CoreToolChoice<TOOLS>;

    /**
Maximum number of sequential LLM calls (steps), e.g. when you use tool calls. Must be at least 1.

A maximum number is required to prevent infinite loops in the case of misconfigured tools.

By default, it's set to 1, which means that only a single LLM call is made.
 */
    maxSteps?: number;

    /**
When enabled, the model will perform additional steps if the finish reason is "length" (experimental).

By default, it's set to false.
     */
    experimental_continueSteps?: boolean;

    /**
Optional telemetry configuration (experimental).
     */
    experimental_telemetry?: TelemetrySettings;

    /**
Additional provider-specific metadata. They are passed through
to the provider from the AI SDK and enable provider-specific
functionality that can be fully encapsulated in the provider.
 */
    experimental_providerMetadata?: ProviderMetadata;

    /**
Limits the tools that are available for the model to call without
changing the tool call and result types in the result.
     */
    experimental_activeTools?: Array<keyof TOOLS>;

    /**
A function that attempts to repair a tool call that failed to parse.
     */
    experimental_repairToolCall?: ToolCallRepairFunction<TOOLS>;

    /**
Enable streaming of tool call deltas as they are generated. Disabled by default.
     */
    experimental_toolCallStreaming?: boolean;

    /**
Optional transformation that is applied to the stream.
     */
    experimental_transform?: (options: {
      tools: TOOLS; // for type inference
    }) => TransformStream<TextStreamPart<TOOLS>, TextStreamPart<TOOLS>>;

    /**
Callback that is called for each chunk of the stream. The stream processing will pause until the callback promise is resolved.
     */
    onChunk?: (event: {
      chunk: Extract<
        TextStreamPart<TOOLS>,
        {
          type:
            | 'text-delta'
            | 'tool-call'
            | 'tool-call-streaming-start'
            | 'tool-call-delta'
            | 'tool-result';
        }
      >;
    }) => Promise<void> | void;

    /**
Callback that is called when the LLM response and all request tool executions
(for tools that have an `execute` function) are finished.

The usage is the combined usage of all steps.
     */
    onFinish?: (
      event: Omit<StepResult<TOOLS>, 'stepType' | 'isContinued'> & {
        /**
Details for all steps.
       */
        readonly steps: StepResult<TOOLS>[];
      },
    ) => Promise<void> | void;

    /**
    Callback that is called when each step (LLM call) is finished, including intermediate steps.
    */
    onStepFinish?: (event: StepResult<TOOLS>) => Promise<void> | void;

    /**
     * Internal. For test use only. May change without notice.
     */
    _internal?: {
      now?: () => number;
      generateId?: () => string;
      currentDate?: () => Date;
    };
  }): StreamTextResult<TOOLS> {
  return new DefaultStreamTextResult({
    model,
    telemetry,
    headers,
    settings,
    maxRetries,
    abortSignal,
    system,
    prompt,
    messages,
    tools,
    toolChoice,
    toolCallStreaming,
    transform: transform?.({ tools: tools as TOOLS }),
    activeTools,
    repairToolCall,
    maxSteps,
    continueSteps,
    providerMetadata,
    onChunk,
    onFinish,
    onStepFinish,
    now,
    currentDate,
    generateId,
  });
}

Comment (Hazi7) [reply src/panel-chat.ts:156]: > Can you please remove this change, since streamText returns a promise and await is required. Thanks

This seems to be just a synchronous method, does not return a Promise.

- [SDK Example:](https://sdk.vercel.ai/docs/reference/ai-sdk-core/stream-text#streamtext)
image

- [Source Code](https://github.com/vercel/ai/blob/main/packages/ai/core/generate-text/stream-text.ts)
```ts
@return
A result object for accessing different stream types and additional information.
 */
export function streamText<TOOLS extends Record<string, CoreTool>>({
  model,
  tools,
  toolChoice,
  system,
  prompt,
  messages,
  maxRetries,
  abortSignal,
  headers,
  maxSteps = 1,
  experimental_continueSteps: continueSteps = false,
  experimental_telemetry: telemetry,
  experimental_providerMetadata: providerMetadata,
  experimental_toolCallStreaming: toolCallStreaming = false,
  experimental_activeTools: activeTools,
  experimental_repairToolCall: repairToolCall,
  experimental_transform: transform,
  onChunk,
  onFinish,
  onStepFinish,
  _internal: {
    now = originalNow,
    generateId = originalGenerateId,
    currentDate = () => new Date(),
  } = {},
  ...settings
}: CallSettings &
  Prompt & {
    /**
The language model to use.
     */
    model: LanguageModel;

    /**
The tools that the model can call. The model needs to support calling tools.
    */
    tools?: TOOLS;

    /**
The tool choice strategy. Default: 'auto'.
     */
    toolChoice?: CoreToolChoice<TOOLS>;

    /**
Maximum number of sequential LLM calls (steps), e.g. when you use tool calls. Must be at least 1.

A maximum number is required to prevent infinite loops in the case of misconfigured tools.

By default, it's set to 1, which means that only a single LLM call is made.
 */
    maxSteps?: number;

    /**
When enabled, the model will perform additional steps if the finish reason is "length" (experimental).

By default, it's set to false.
     */
    experimental_continueSteps?: boolean;

    /**
Optional telemetry configuration (experimental).
     */
    experimental_telemetry?: TelemetrySettings;

    /**
Additional provider-specific metadata. They are passed through
to the provider from the AI SDK and enable provider-specific
functionality that can be fully encapsulated in the provider.
 */
    experimental_providerMetadata?: ProviderMetadata;

    /**
Limits the tools that are available for the model to call without
changing the tool call and result types in the result.
     */
    experimental_activeTools?: Array<keyof TOOLS>;

    /**
A function that attempts to repair a tool call that failed to parse.
     */
    experimental_repairToolCall?: ToolCallRepairFunction<TOOLS>;

    /**
Enable streaming of tool call deltas as they are generated. Disabled by default.
     */
    experimental_toolCallStreaming?: boolean;

    /**
Optional transformation that is applied to the stream.
     */
    experimental_transform?: (options: {
      tools: TOOLS; // for type inference
    }) => TransformStream<TextStreamPart<TOOLS>, TextStreamPart<TOOLS>>;

    /**
Callback that is called for each chunk of the stream. The stream processing will pause until the callback promise is resolved.
     */
    onChunk?: (event: {
      chunk: Extract<
        TextStreamPart<TOOLS>,
        {
          type:
            | 'text-delta'
            | 'tool-call'
            | 'tool-call-streaming-start'
            | 'tool-call-delta'
            | 'tool-result';
        }
      >;
    }) => Promise<void> | void;

    /**
Callback that is called when the LLM response and all request tool executions
(for tools that have an `execute` function) are finished.

The usage is the combined usage of all steps.
     */
    onFinish?: (
      event: Omit<StepResult<TOOLS>, 'stepType' | 'isContinued'> & {
        /**
Details for all steps.
       */
        readonly steps: StepResult<TOOLS>[];
      },
    ) => Promise<void> | void;

    /**
    Callback that is called when each step (LLM call) is finished, including intermediate steps.
    */
    onStepFinish?: (event: StepResult<TOOLS>) => Promise<void> | void;

    /**
     * Internal. For test use only. May change without notice.
     */
    _internal?: {
      now?: () => number;
      generateId?: () => string;
      currentDate?: () => Date;
    };
  }): StreamTextResult<TOOLS> {
  return new DefaultStreamTextResult({
    model,
    telemetry,
    headers,
    settings,
    maxRetries,
    abortSignal,
    system,
    prompt,
    messages,
    tools,
    toolChoice,
    toolCallStreaming,
    transform: transform?.({ tools: tools as TOOLS }),
    activeTools,
    repairToolCall,
    maxSteps,
    continueSteps,
    providerMetadata,
    onChunk,
    onFinish,
    onStepFinish,
    now,
    currentDate,
    generateId,
  });
}

Comment (mohankumarelec) [reply src/panel-chat.ts:156]: Hi @Hazi7 , The documentation you are seeing is for v4 of AI sdk , but the project currently uses v3 of AI sdk , where the function is async.

You find more details below.
https://sdk.vercel.ai/docs/migration-guides/migration-guide-4-0#streamtext-returns-immediately

**Comment by Hazi7** [comment]
Hi @mohankumarelec , thank you for pointing out my mistake. I have made the necessary changes to the commit. Could you please take a look? Thank you.

File: src/panel-chat.ts (hunk 1 above)
Comment (Hazi7) [reply src/panel-chat.ts]: Hi @mohankumarelec , thank you for pointing out my mistake. I have made the necessary changes to the commit. Could you please take a look? Thank you.
